### ISSUE TITLE
the welcome plugin is not installed during init then start in mfserv

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfserv#230]
```
- Installing internal plugin: welcome...                   [ RUNNING ]Traceback (most recent call last):
  File "/opt/metwork-mfcom-0.8/bin/_install_or_update_configured_plugins.py", line 60, in <module>
    i_plugin("internal", plugin, selected_file)
  File "/opt/metwork-mfcom-0.8/bin/_install_or_update_configured_plugins.py", line 20, in i_plugin
    install_plugin(fil)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 527, in install_plugin
    ignore_errors=ignore_errors, quiet=quiet)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 496, in _execute_with_lock
    return fn(*args, **kwargs)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 489, in _install_plugin
    bash_wrapper=postinstall_status)
mfutil.plugins.MFUtilPluginCantInstall: BashWrapperException with message: can't install plugin welcome and debug: 
===== BASH COMMAND =======================
_plugins.postinstall welcome 0.8.ci397.d3baf9a 1
===== BASH RETURN CODE ===================
1
===== BASH STDOUT ========================
Testing circus conf generation...
Ok
Testing nginx conf generation...
```

**Comment by thefab** [comment]
the first time only...
