### ISSUE TITLE
make develop issue

### ISSUE THREAD

**Issue by mpup371** [metwork-framework/mfserv#263]
Hi,
when reinstall with metwork-stable (0.8), I get **MFUtilPluginBaseNotInitialized** with "make develop":

# to force an autorestart
touch config.ini
_plugins.develop wsbdpe
- Devlinking plugin wsbdpe...                              [ RUNNING ]Traceback (most recent call last):
  File "/opt/metwork-mfcom-0.8/opt/python3/bin/_plugins.develop", line 12, in <module>
    sys.exit(main())
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/cli_tools/plugins_develop.py", line 21, in main
    develop_plugin(args.plugin_path, args.name)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 591, in develop_plugin
    ignore_errors=ignore_errors, quiet=quiet)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 496, in _execute_with_lock
    return fn(*args, **kwargs)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 566, in _develop_plugin
    bash_wrapper=postinstall_status)
mfutil.plugins.MFUtilPluginCantInstall: BashWrapperException with message: can't install plugin wsbdpe and debug: 
===== BASH COMMAND =======================
_plugins.postinstall wsbdpe dev_link dev_link
===== BASH RETURN CODE ===================
1
===== BASH STDOUT ========================
[DEBUG]: loading local@mfserv[/home/mfserv/wsbdpe/local]
Looking in links: /home/mfserv/wsbdpe/python3_virtualenv_sources/src
Requirement already satisfied: certifi==2019.3.9 in /opt/metwork-mfext-0.8/opt/python3_core/lib/python3.7/site-packages (from -c /opt/metwork-mfext-0.8/opt/python3/lib/python3.7/site-packages/requirements3.txt (line 21)) (2019.3.9)
Requirement already satisfied: falcon==2.0.0 in /home/mfserv/wsbdpe/local/lib/python3.7/site-packages (from -r requirements3.txt.tmp (line 2)) (2.0.0)
Requirement already satisfied: nose==1.3.7 in /home/mfserv/wsbdpe/local/lib/python3.7/site-packages (from -r requirements3.txt.tmp (line 3)) (1.3.7)
Requirement already satisfied: psycopg2==2.8.4 in /home/mfserv/wsbdpe/local/lib/python3.7/site-packages (from -r requirements3.txt.tmp (line 4)) (2.8.4)
===== BASH STDERR ========================
Traceback (most recent call last):
  File "/opt/metwork-mfcom-0.8/opt/python3/bin/plugins.info", line 12, in <module>
    sys.exit(main())
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/cli_tools/plugins_info.py", line 25, in main
    plugins_base_dir=args.plugins_base_dir)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 692, in get_plugin_info
    _assert_plugins_base_initialized(plugins_base_dir)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 279, in _assert_plugins_base_initialized
    raise MFUtilPluginBaseNotInitialized()
mfutil.plugins.MFUtilPluginBaseNotInitialized
Traceback (most recent call last):
  File "/opt/metwork-mfcom-0.8/opt/python3/bin/plugins.info", line 12, in <module>
    sys.exit(main())
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/cli_tools/plugins_info.py", line 25, in main
    plugins_base_dir=args.plugins_base_dir)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 692, in get_plugin_info
    _assert_plugins_base_initialized(plugins_base_dir)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 279, in _assert_plugins_base_initialized
    raise MFUtilPluginBaseNotInitialized()
mfutil.plugins.MFUtilPluginBaseNotInitialized
Traceback (most recent call last):
  File "/opt/metwork-mfcom-0.8/opt/python3/bin/plugins.info", line 12, in <module>
    sys.exit(main())
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/cli_tools/plugins_info.py", line 25, in main
    plugins_base_dir=args.plugins_base_dir)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 692, in get_plugin_info
    _assert_plugins_base_initialized(plugins_base_dir)
  File "/opt/metwork-mfcom-0.8/opt/python3/lib/python3.7/site-packages/mfutil-0.0.0-py3.7.egg/mfutil/plugins.py", line 279, in _assert_plugins_base_initialized
    raise MFUtilPluginBaseNotInitialized()
mfutil.plugins.MFUtilPluginBaseNotInitialized
make: *** [develop] Erreur 1
[mfserv:~/wsbdpe] $

**Comment by thefab** [comment]
start the module before ?

**Comment by mpup371** [comment]
yes !!!
not obvious ...

**Comment by thefab** [comment]
IMHO it's already very clear but as it is a recurrent question, I opened #266 for a more clear warning
