### ISSUE TITLE
ModuleNotFoundError (coverage) while releasing a plugin

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfserv#434]
While executing `make release` on a mfserv plugin (template default), I face the below error :
(PYTHONVERBOSE=1)
```
Traceback (most recent call last):
  File "/opt/metwork-mfext-0.9/opt/python3_core/lib/python3.7/site.py", line 518, in execsitecustomize
    import sitecustomize
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/metwork-mfext-0.9/opt/python3_core/lib/python3.7/site-packages/sitecustomize.py", line 1, in <module>
    import coverage
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'coverage'
```
I do not use the library `coverage` in my plugin.

The bypass I found is to add `python3_devtools@mfext` in file .layerapi2_dependencies.

**Comment by matthieumarrast** [comment]
My mistake. Sorry.
